spring:
  application:
    name: service-blog
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.171.200/xpz_blog?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  cloud:
    nacos:
      server-addr: 192.168.171.200:8849
  jackson:
    time-zone: GMT+8
  # 文件上传大小限制
  servlet:
    multipart:
      max-file-size: 4MB
  redis:
    host: 192.168.171.200
    port: 6380
server:
  port: 9002
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/com/lj/blog/mapper/xml/*.xml
tencent:
  cos:
    file:
      region: ap-nanjing
      secretid: AKIDmQt56uUp5DD1b2NceT5T6ZrvlNm01oQn
      secretkey: PiogKxQwHPNAlANTREpDONHzUmsqdEy1
      bucketname: bucket-01-1311694956
easy-es:
  enable: true #默认为true,若为false则认为不启用本框架
  address : 192.168.171.200:9200 # es的连接地址,必须含端口 若为集群,则可以用逗号隔开 例如:127.0.0.1:9200,127.0.0.2:9200
